name: test_app_dionke
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  auto_route: 7.8.3
  get_it: ^7.7.0
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  auto_route_generator: ^7.3.1

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true
